# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xao1wgrLYh1xtafJ_4c5yFcvZcd8vacO

# Part 1: Iris Flower Classification - Model Preparation
First, we will train a Random Forest model and save it using pickle.
"""

import pandas as pd
import pickle
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Train Random Forest Model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X, y)

# Save the model to a pickle file
with open('iris_model.pkl', 'wb') as f:
    pickle.dump(model, f)

print("Model saved as iris_model.pkl")

"""## Create the Streamlit App (`app.py`)
This cell writes the code for the web interface.
"""

app_code = """import streamlit as st
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# Load the Iris dataset
iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.DataFrame(iris.target, columns=['target'])

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train.values.ravel())

# Streamlit app
st.title("Iris Flower Species Classification")
st.write("This app uses a RandomForestClassifier to classify Iris flower species based on their features.")

# Sidebar for user input
st.sidebar.header('User Input Features')

def user_input_features():
    sepal_length = st.sidebar.slider('Sepal length', float(X['sepal length (cm)'].min()), float(X['sepal length (cm)'].max()), float(X['sepal length (cm)'].mean()))
    sepal_width = st.sidebar.slider('Sepal width', float(X['sepal width (cm)'].min()), float(X['sepal width (cm)'].max()), float(X['sepal width (cm)'].mean()))
    petal_length = st.sidebar.slider('Petal length', float(X['petal length (cm)'].min()), float(X['petal length (cm)'].max()), float(X['petal length (cm)'].mean()))
    petal_width = st.sidebar.slider('Petal width', float(X['petal width (cm)'].min()), float(X['petal width (cm)'].max()), float(X['petal width (cm)'].mean()))
    data = {'sepal length (cm)': sepal_length,
            'sepal width (cm)': sepal_width,
            'petal length (cm)': petal_length,
            'petal width (cm)': petal_width}
    features = pd.DataFrame(data, index=[0])
    return features

input_df = user_input_features()
prediction = clf.predict(input_df)
prediction_proba = clf.predict_proba(input_df)

st.subheader('Prediction')
iris_species = ['Setosa', 'Versicolour', 'Virginica']
st.write(iris_species[prediction[0]])

st.subheader('Prediction Probability')
st.write(prediction_proba)"""

with open('app.py', 'w') as f:
    f.write(app_code)

print("app.py updated successfully.")

"""## Create `requirements.txt`"""

requirements = """
streamlit==1.30.0
scikit-learn==1.3.0
pandas==2.0.3
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements.strip())

print("requirements.txt created.")

"""# Part 2: SMS Spam Detection Deployment
In this section, we build the SMS Spam classifier, save the model components, and prepare the deployment files.
"""

import pandas as pd
import pickle
import requests
import io
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# Step 1: Download and Load Dataset
url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"
response = requests.get(url)

# Save the raw file as SMSSpamCollection
with open('SMSSpamCollection', 'w') as f:
    f.write(response.text)

# Load into DataFrame
df = pd.read_table(io.StringIO(response.text), header=None, names=['label', 'message'])

# Step 2: Training
X = df['message']
y = df['label']
vectorizer = CountVectorizer()
X_vec = vectorizer.fit_transform(X)
model = MultinomialNB()
model.fit(X_vec, y)

# Step 3: Save required deployment elements
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)
with open('vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

print("Files created: SMSSpamCollection, model.pkl, vectorizer.pkl")

"""## Create `spam.py` and `requirements.txt` for the Spam App"""

spam_app_code = """
import streamlit as st
import pickle

# Load model and vectorizer
model = pickle.load(open('model.pkl', 'rb'))
vectorizer = pickle.load(open('vectorizer.pkl', 'rb'))

st.title('SMS Spam Detection App')
user_input = st.text_area('Enter SMS Message Here:')

if st.button('Detect'):
    if user_input.strip():
        vect = vectorizer.transform([user_input]).toarray()
        prediction = model.predict(vect)[0]
        if prediction == 'spam':
            st.error(f'Result: {prediction.upper()}')
        else:
            st.success(f'Result: {prediction.upper()}')
"""

with open('spam.py', 'w') as f:
    f.write(spam_app_code)

with open('requirements_spam.txt', 'w') as f:
    f.write('joblib\npandas\nscikit-learn\nstreamlit')

print("spam.py and requirements_spam.txt created.")

"""# Part 2: SMS Spam Detection Deployment
In this section, we build the SMS Spam classifier using Naive Bayes, save the model and vectorizer, and prepare the deployment files.
"""

import pandas as pd
import pickle
import requests
import io
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

# Step 1: Download and Load Dataset
url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"
response = requests.get(url)

# Load into DataFrame
df = pd.read_table(io.StringIO(response.text), header=None, names=['label', 'message'])

# Save the raw file as requested in Step 3 of the guide
with open('SMSSpamCollection', 'w') as f:
    f.write(response.text)

# Step 2: Preprocessing and Training
X = df['message']
y = df['label']

vectorizer = CountVectorizer()
X_vec = vectorizer.fit_transform(X)

model = MultinomialNB()
model.fit(X_vec, y)

# Step 3: Save required deployment elements
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

with open('vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

print("Part 2 files created: SMSSpamCollection, model.pkl, vectorizer.pkl")

"""## Create the Streamlit App for Spam Detection (`spam.py`)"""

spam_app_code = """
import streamlit as st
import pickle

# Load model and vectorizer
model = pickle.load(open('model.pkl', 'rb'))
vectorizer = pickle.load(open('vectorizer.pkl', 'rb'))

st.title('SMS Spam Detection App')
st.write('Enter an SMS message below to check if it is Spam or Ham.')

user_input = st.text_area("Enter SMS Message Here:")

if st.button('Detect'):
    if user_input.strip() != '':
        data = [user_input]
        vect = vectorizer.transform(data).toarray()
        prediction = model.predict(vect)
        result = prediction[0]

        if result == 'spam':
            st.error(f'Result: This message is {result.upper()}')
        else:
            st.success(f'Result: This message is {result.upper()}')
    else:
        st.warning("Please enter some text.")
"""

with open('spam.py', 'w') as f:
    f.write(spam_app_code)

print("spam.py created.")

"""## Create `requirements.txt` for Spam App"""

spam_reqs = """
joblib
pandas
scikit-learn
streamlit
"""

with open('requirements_spam.txt', 'w') as f:
    f.write(spam_reqs.strip())

print("requirements_spam.txt created. (Rename to requirements.txt when uploading to the 'spam' repo)")